spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:postgres}:${DB_PORT:5432}/${DB_NAME:krakow_parking}
    username: ${DB_USER:parking_user}
    password: ${DB_PASSWORD:parking_pass}
  jpa:
    show-sql: false
  data:
    redis:
      host: ${REDIS_HOST:redis}
      port: ${REDIS_PORT:6379}
